### ISSUE TITLE
엔드게임

### ISSUE THREAD

**Issue by eunjung-jenny** [woowa-techcamp-2020/bmart-1#154]
- [ ] Product 불러오는 개수 10개 정도로 줄이기
- [x] ProductItem 버그 (pointerup, 수평 스크롤) @eunjung-jenny 
- [x] 서치 드로어 달기 @eunjung-jenny 
- [ ] ProductItem 더블탭 @eunjung-jenny 
- [ ] 장바구니 페이지 결제하기 최하단에 고정 @eunjung-jenny
- [x] 장바구니 마쁠 가로 길이 조정 @jhaemin 
- [x] 로그아웃시 최근 검색어 초기화 @eunjung-jenny 
- [ ] 검색창 input 초기화 @eunjung-jenny 
- [x] ~~비회원의 찜~~ | 장바구니 담기 @eunjung-jenny 
- [x] 장바구니 담겨있는 상품의 상세페이지에 개수 표시 @eunjung-jenny 
- [x] warning: 상품 상세 img에 alt @eunjung-jenny 
- [x] 뒤로가기 달기 @jhaemin 
- [x] 숏컷 (장바구니 | 검색) 달기 @jhaemin 
- [x] 무조건 보이는 텅 @agrajak
- [x] 무조건 보이는 로그인 버튼 @jhaemin 
- [x] 페이지별 레이지로딩 @agrajak
- [x] 무한스크롤 @jhaemin 
- [x] 카테고리에서 뒤로 가기 누르면 이전 카테고리가 아니라 홈으로? @agrajak 
- [x] 슬롯 머신 초기화면에서 안됨 @agrajak 
- [x] 슬롯 머신 정렬 수정 @agrajak 
- [x] 로딩이 느린 모든 문제
- [ ] 각종 페이지 필요한 경우 user-select: none 처리 @eunjung-jenny 
- [x] 홈 화면에서 스크롤 내리다가 토픽 컨테이너에서 잠시 멈춤
- [x] 찜 페이지 새로고침 @agrajak 
- [x] 배송지 관리 페이지 다크모드 @eunjung-jenny 
- [x] 뒤로 가기 할 때 스크롤 위치 유지 @jhaemin 
- [ ] 카테고리나 정렬 선택하는 드로어 : 스크롤 동작에서 선택되는 이슈 @agrajak 
- [ ] 딸기 검색에 전복이 나온다
- [x] 데스크탑에서 배너를 이동할 수 없음 @jhaemin 
- [x] 숏컷이 있는 페이지에서 아래 패딩 확장 @jhaemin 
- [x] Favicon @jhaemin 
- [x] 로그아웃 상태에서 배송지 페이지 접근 막기
- [x] 상품 캐시

**Comment by eunjung-jenny** [comment]
ProductItem 버그 (pointerup, 수평 스크롤)

**Comment by eunjung-jenny** [comment]
- [ ] 뒤로가기 달기

**Comment by agrajak** [comment]
[ ] CategoryDetails에서 초기 로딩 전에 잠깐 텅 이라고 표시됨

**Comment by eunjung-jenny** [comment]
- [ ] 장바구니 | 검색 숏컷 달기

**Comment by agrajak** [comment]
- [ ] 퍼포먼스 개선 (페이지 별 레이지로딩)

**Comment by eunjung-jenny** [comment]
- [ ] 서치 드로어

**Comment by agrajak** [comment]
- [ ] 카테고리에서 뒤로가기를 누르면 이전 카테고리 정보가 아니라 홈으로 되돌아가는게 좋을 거 같음

**Comment by agrajak** [comment]
- [ ] 슬롯 머신 초기화면에서 안됨 (왜 모바일에서는 잘됨...?)

**Comment by eunjung-jenny** [comment]
- [ ] 슬롯머신 위치 수정

**Comment by agrajak** [comment]
- [ ] CategoryDetails에서 30개씩 들고오니까 너무 느림. 10개씩 들고와도 될 거 같음

**Comment by eunjung-jenny** [comment]
- [ ] 홈화면 주제별 칸에 스켈레톤 나오게 해야하나? 높이가 없다가 생김 | 좌우 스크롤시에도 마찬가지로 안보이다가 보임

**Comment by agrajak** [comment]
- [ ] 홈 화면 쭉 내리다가 토픽 컨테이너에서 잠깐 멈춤

**Comment by eunjung-jenny** [comment]
- [ ] 각종 페이지 user-select: none 처리

**Comment by eunjung-jenny** [comment]
- [ ] ProductItem longpress 안좋아

**Comment by eunjung-jenny** [comment]
- [ ] 찜 페이지 새로고침

**Comment by eunjung-jenny** [comment]
- [ ] 장바구니 결제하기 아래에 고정 | 마쁠 가로 조절

**Comment by jhaemin** [comment]
- [ ] 로그인 화면 리로드할 때 무조건 로그인 버튼이 나옴
- [ ] 뒤로 갈 때 스크롤 위치가 유지되지 않음

**Comment by eunjung-jenny** [comment]
- [ ] 배송지 관리 페이지 다크모드
