### ISSUE TITLE
API 하나 구현하기

### ISSUE THREAD

**Issue by Agrajak** [woowa-techcamp-2020/bmart-1#5]
- API 하나를 같이 구현하면서 프로젝트 구조 및 간단한 컨벤션 같이 정하기
- /api/me 기본 구현
- 미들웨어에서 req.auth에 유저 정보가 담긴 (userID) Object를 담고 있는 걸로 합시다!!

**Comment by eunjung-jenny** [comment]
prisma 너무 멋져욥!
